# See https://github.com/silverstripe/silverstripe-travis-support for setup details

sudo: false

dist: trusty

language: php

env:
  - DB=MYSQL CORE_RELEASE=3.6

matrix:
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
      env: DB=PGSQL CORE_RELEASE=3
    - php: 5.6
      env: DB=PGSQL CORE_RELEASE=3.6
    - php: 7.1

before_script:
  - composer self-update || true
  - git clone git://github.com/silverstripe/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss

script:
  - vendor/bin/phpunit reports/tests
